version: '3.8'
services:
  mysql:
    image: mysql:latest
    ports:
      - '3308:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MY_DATABASE: test_nestjs
      MYSQL_USER: root'@'localhost
      MYSQL_PASSWORD: Hoang2k@123
    volumes:
      - ./data/mysql:/var/lib/mysql
